끄투 en_US.json 영어 번역 완료.
JJoriping/KKuTu pull request #260
Opened 2018-01-21 08:12 UTC by hatty163

끄투닷넷에 시범적으로 적용한 영어 번역본 오류를 수정하여 PR 올립니다.

문법 실수 있으면 지적 바랍니다.

2018-01-26 14:40 UTC, hatty163 commented
언어 선택 스크립트를 kkutu.pug / portal.pug 하단에 삽입하였습니다.

2018-01-26 14:49 UTC, hatty163 commented
모바일 레이아웃에도 표시되게 수정하였으며, 실수로 낸 코드 오류를 수정하였습니다.

2018-02-24 15:36 UTC, JJoriping requested changes
안녕하세요. 영어로 번역을 시도해 주셔서 정말 감사드리며 대단히 수고하셨습니다. 다만 번역에 오탈자가 많이 보이고 어색한 부분이 조금 있어 본 레포지토리에 포함시키기에는 다소 무리가 있어 보입니다. 다시 한 번 끄투에 대한 성원에 감사드립니다.

* 동일한 기능을 하는 구현은 중복해 작성하지 말고 파일 `./Server/lib/Web/views/module.pug`에 작성하면 좋습니다.

2019-08-02 10:39 UTC, closed without merging

2024-10-31 11:14 UTC, 1ongames commented
이미 진작에 닫힌 pr이지만, Node.js 16.6.2 기준 정상 작동하지 않는 것으로 확인되었습니다